### ISSUE TITLE
Does the main model include unit-fixed effects?

### ISSUE THREAD

**Issue by Halvard123** [setzler/eventStudy#21]
Hey,

Following your suggestion, I will split the original post into separate questions.

First of all, I wonder whether the main model includes unit-fixed effects or whether the fixed-effects are on the cohort level. This of course influences the role of the covariates, which is the main reason why I am asking. I am also asking because Abraham and Sun (2018) include the i-subscript for alpha in their algebraic setup for Y_it in event studies, which typically implies unit-fixed effects for unit i, while the practical guide for event studies you have published does not. 

My question could also be phrased to be directly about the covariates since the absence of unit-fixed effects allows for fixed controls such as gender and nationality. Does the model only allow for the inclusion of covariates that change over time for individuals or are fixed controls allowed?

Best,
Halvard

**Comment by davidnov** [comment]
Hi @Halvard123 

The main model, by default, includes cohort fixed effects, not unit fixed effects. More accurately, the model includes a set of cohort fixed effects that saturate the model. 

To make this a bit more concrete, consider a panel where units are observed from 1999 to 2003 and units are treated in 2001 to 2003. Let's focus on the cohort treated in 2001 (i.e., the reference cohort) and suppose that we use 1999 as the omitted year. Their control group at their time 0 includes the 2002 and 2003 treated -- let's call this DiD sample 1. Meanwhile, at time +1, the control group only includes the 2003 treated -- let's call this DiD sample 2.

By construction, the package will "stack" these two samples and the model will have fixed effects for cohort X DiD sample (dropping unused interactions). More generally, with multiple treated reference cohorts, the model has reference cohort X cohort X DiD sample fixed effects -- this ensures that the overall regression matches what one would estimate if manually estimating each reference cohort X event-time coefficient.

To use unit fixed effects instead of cohort fixed effects in the above, use the `add_units_fes = TRUE` setting `(add_units_fes = FALSE` is the default). Note that to identify these fixed effects, you will require two observations per individual in each reference cohort X DiD sample. In other words, this will essentially impose a balanced panel in each reference cohort X DiD sample.

**Comment by Halvard123** [comment]
Thank you David, this answers several of my concerns. 

One thing that is still somewhat unclear to me is the aggregation of these heterogeneous results, and this is of course quite important as those estimates generally are the primary results of a study as there may be many treatment cohorts and we are interested in some degree of generality. 

Then, for the pooled and cohort-weighted estimates, are both of these estimations simply weighting schemes used on the heterogeneous reference cohort X event-time results? Or is it the case that the estimation method is slightly different when we assume homogeneous effects in terms of which fixed effects interactions are included?

Best,
Halvard

**Comment by davidnov** [comment]
For the cohort-weighted estimates, this is an ex-post weighting scheme (e.g,. using cohort size as the weights) using the underlying reference-cohort X event-time estimates. For the pooled estimates, we build the parametric assumption that event-time estimates don't vary across cohorts into the estimating equation and let OLS do the weighting.

**Comment by Halvard123** [comment]
I see, that is more or less what I assumed was the case.

Thank you for the help with this as well as the other issues, it is highly appreciated and will surely prove helpful with regards to the future event study analysis. 

H
